# wxWidgets CI/CD Pipeline - Main Workflow
# Task: cb9a80 - Set up CI/CD pipelines with security gates
# Owner: @test_stabilize
# Target: <10 minute build time, 80% coverage

name: CI/CD - wxWidgets

on:
  push:
    branches: [master, main, develop, 'feature/**', 'release/**']
  pull_request:
    branches: [master, main, develop]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

env:
  # Build configuration
  CMAKE_BUILD_TYPE: Release
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  # Coverage targets
  COVERAGE_TARGET: 80
  # Test configuration
  GTEST_COLOR: 1

jobs:
  # ====================
  # STAGE 1: Build & Test
  # ====================

  build-matrix:
    name: Build & Test (${{ matrix.os }}, ${{ matrix.compiler }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang]
        exclude:
          - os: windows-latest
            compiler: clang
        include:
          - os: ubuntu-latest
            compiler: gcc
            cc: gcc-13
            cxx: g++-13
          - os: ubuntu-latest
            compiler: clang
            cc: clang-15
            cxx: clang++-15
          - os: macos-latest
            compiler: gcc
            cc: gcc-13
            cxx: g++-13
          - os: macos-latest
            compiler: clang
            cc: clang
            cxx: clang++
          - os: windows-latest
            compiler: gcc
            cc: gcc
            cxx: g++

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up build environment (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ${{ matrix.cc }} ${{ matrix.cxx }} \
            cmake ninja-build ccache \
            libgtk-3-dev libx11-dev libgl1-mesa-dev \
            libglu1-mesa-dev libpng-dev libjpeg-dev \
            libtiff-dev libexpat1-dev libnotify-dev \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libwebkit2gtk-4.0-dev

      - name: Set up build environment (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install cmake ninja ccache

      - name: Set up build environment (Windows)
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.os }}-${{ matrix.compiler }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ matrix.os }}-${{ matrix.compiler }}-

      - name: Configure CMake
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
            -DCMAKE_CXX_STANDARD=17 \
            -DwxBUILD_SHARED=ON \
            -DwxBUILD_TESTS=ON \
            -DwxBUILD_SAMPLES=OFF \
            -DwxUSE_STL=ON \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: |
          cmake --build build --config ${{ env.CMAKE_BUILD_TYPE }} --parallel

      - name: Run unit tests
        run: |
          cd build
          ctest --output-on-failure --parallel --build-config ${{ env.CMAKE_BUILD_TYPE }}

      - name: Upload build artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.os }}-${{ matrix.compiler }}
          path: |
            build/CMakeFiles/CMakeOutput.log
            build/CMakeFiles/CMakeError.log
            build/Testing/Temporary/

  # Coverage analysis (Linux only for speed)
  coverage:
    name: Code Coverage Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: build-matrix

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-13 g++-13 cmake ninja-build \
            libgtk-3-dev libx11-dev \
            lcov gcov

      - name: Configure with coverage
        env:
          CC: gcc-13
          CXX: g++-13
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_STANDARD=17 \
            -DwxBUILD_TESTS=ON \
            -DCMAKE_CXX_FLAGS="--coverage -fprofile-arcs -ftest-coverage" \
            -DCMAKE_C_FLAGS="--coverage -fprofile-arcs -ftest-coverage"

      - name: Build with coverage
        run: cmake --build build --parallel

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure --parallel

      - name: Generate coverage report
        run: |
          lcov --directory build --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/tests/*' '*/samples/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload to CodeCov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.info
          flags: unittests
          name: wxwidgets-coverage
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Check coverage threshold
        run: |
          COVERAGE=$(lcov --summary coverage.info 2>&1 | grep lines | awk '{print $2}' | sed 's/%//')
          echo "Coverage: ${COVERAGE}%"
          if (( $(echo "$COVERAGE < ${{ env.COVERAGE_TARGET }}" | bc -l) )); then
            echo "::warning::Coverage ${COVERAGE}% is below target ${{ env.COVERAGE_TARGET }}%"
          else
            echo "::notice::Coverage ${COVERAGE}% meets target ${{ env.COVERAGE_TARGET }}%"
          fi

      - name: Generate coverage badge
        if: github.ref == 'refs/heads/master'
        run: |
          COVERAGE=$(lcov --summary coverage.info 2>&1 | grep lines | awk '{print $2}' | sed 's/%//')
          COLOR="red"
          if (( $(echo "$COVERAGE >= 80" | bc -l) )); then COLOR="brightgreen"
          elif (( $(echo "$COVERAGE >= 60" | bc -l) )); then COLOR="yellow"
          elif (( $(echo "$COVERAGE >= 40" | bc -l) )); then COLOR="orange"
          fi
          echo "Coverage: ${COVERAGE}% (${COLOR})"

  # ====================
  # STAGE 3: Integration Tests
  # ====================

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build-matrix

    services:
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up integration test environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-13 g++-13 cmake ninja-build \
            libgtk-3-dev libx11-dev \
            redis-tools

      - name: Build integration tests
        env:
          CC: gcc-13
          CXX: g++-13
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DwxBUILD_TESTS=ON
          cmake --build build --target integration-tests --parallel

      - name: Run integration tests
        run: |
          cd build
          ctest -L integration --output-on-failure

  # ====================
  # Build Summary
  # ====================

  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [build-matrix, coverage, integration-tests]
    if: always()

    steps:
      - name: Generate summary
        run: |
          cat <<EOF > $GITHUB_STEP_SUMMARY
          # wxWidgets CI/CD Pipeline Summary

          ## Build Status
          - **Build Matrix**: ${{ needs.build-matrix.result }}
          - **Coverage**: ${{ needs.coverage.result }}
          - **Integration Tests**: ${{ needs.integration-tests.result }}

          ## Metrics
          - Workflow: ${{ github.workflow }}
          - Commit: ${{ github.sha }}
          - Branch: ${{ github.ref_name }}
          - Triggered by: ${{ github.event_name }}

          ## Next Steps
          - Security scanning runs in parallel (see security.yaml workflow)
          - Deployment triggered on successful merge to master

          ---
          **Status**: ${{ job.status }} | **Time**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          EOF

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const summary = `## 🔨 Build Summary

            | Job | Status |
            |-----|--------|
            | Build Matrix | ${{ needs.build-matrix.result }} |
            | Coverage | ${{ needs.coverage.result }} |
            | Integration Tests | ${{ needs.integration-tests.result }} |

            **Next**: Security scanning and deployment checks running in parallel workflows.
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });

  # ====================
  # Quality Gates
  # ====================

  quality-gate:
    name: Quality Gate Check
    runs-on: ubuntu-latest
    needs: [build-matrix, coverage, integration-tests]
    if: always()

    steps:
      - name: Check all jobs passed
        run: |
          if [ "${{ needs.build-matrix.result }}" != "success" ]; then
            echo "::error::Build matrix failed"
            exit 1
          fi
          if [ "${{ needs.coverage.result }}" != "success" ]; then
            echo "::error::Coverage analysis failed"
            exit 1
          fi
          if [ "${{ needs.integration-tests.result }}" != "success" ]; then
            echo "::error::Integration tests failed"
            exit 1
          fi
          echo "::notice::All quality gates passed ✅"

# Performance targets:
# - Build time: <15 minutes per matrix job
# - Coverage: ≥80% line coverage
# - Integration tests: <10 minutes
# - Total pipeline: <30 minutes (parallel execution)
